/**
 * Stable, machine-readable error codes (spec §6).
 * Returned in the `code` member of every problem+json response.
 * Add codes here as modules are built — never rename existing ones.
 */
export enum ErrorCode {
  // generic
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  INTERNAL = 'INTERNAL',
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',

  // tenancy
  TENANT_HEADER_MISSING = 'TENANT_HEADER_MISSING',
  TENANT_MISMATCH = 'TENANT_MISMATCH',

  // auth & identity
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  SUBDOMAIN_TAKEN = 'SUBDOMAIN_TAKEN',
  EMAIL_TAKEN = 'EMAIL_TAKEN',
  INVITE_INVALID = 'INVITE_INVALID',
  BRAND_MODE_ALREADY_CONFIGURED = 'BRAND_MODE_ALREADY_CONFIGURED',

  // property
  BRAND_LIMIT_SINGLE_MODE = 'BRAND_LIMIT_SINGLE_MODE',
  INVALID_TIMEZONE = 'INVALID_TIMEZONE',
  BRANCH_NAME_TAKEN = 'BRANCH_NAME_TAKEN',
  ROOM_NUMBERS_TAKEN = 'ROOM_NUMBERS_TAKEN',
  INVALID_STATUS_TRANSITION = 'INVALID_STATUS_TRANSITION',

  // reservations
  RESERVATION_NOT_AVAILABLE = 'RESERVATION_NOT_AVAILABLE',
  OVERBOOKING_NOT_ACKNOWLEDGED = 'OVERBOOKING_NOT_ACKNOWLEDGED',

  // folios & money
  FOLIO_NOT_SETTLED = 'FOLIO_NOT_SETTLED',

  // night audit
  AUDIT_ALREADY_RAN = 'AUDIT_ALREADY_RAN',

  // shifts
  SHIFT_ALREADY_OPEN = 'SHIFT_ALREADY_OPEN',
  SHIFT_ALREADY_CLOSED = 'SHIFT_ALREADY_CLOSED',
}
